spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_koylin?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
server:
  port: 8080
  context-path: /
